from __future__ import annotations

from astock.logic_pool.models import LogicSpec
from astock.logic_pool.registry import LogicRegistry


DEFAULT_LOGICS: tuple[LogicSpec, ...] = (
    LogicSpec(
        logic_id="trend_pullback",
        name="主线趋势回踩",
        description="主线方向中，强趋势个股首次回踩短期均线并保持资金承接。",
        regime_whitelist=["trend"],
        required_datasets=["stock_hist", "stock_fund_flow", "stock_indicators", "sector_fund_flow_rank"],
        ranking_rule="prefer positive fund flow and shallow pullback",
        holding_days=3,
        entry_rule={
            "trend_strength_min_5d": 12.0,
            "pullback_max_from_high_pct": 5.0,
            "must_hold_ma5": True,
        },
        exit_rule={"take_profit_pct": 8.0, "max_holding_days": 3},
        invalid_rule={"break_ma10": True, "single_day_drawdown_pct": 5.0},
    ),
    LogicSpec(
        logic_id="leader_first_pullback",
        name="龙头首次分歧回踩",
        description="高辨识度强势股加速后首次充分分歧，观察是否出现承接修复。",
        regime_whitelist=["trend", "rotation"],
        required_datasets=["stock_limit_up_pool", "stock_hist", "stock_fund_flow", "stock_spot"],
        ranking_rule="prefer first pullback after 1-2 expansion bars",
        holding_days=2,
        entry_rule={"recent_limit_up_days": 3, "first_pullback_only": True},
        exit_rule={"take_profit_pct": 6.0, "max_holding_days": 2},
        invalid_rule={"lose_previous_day_low": True},
    ),
    LogicSpec(
        logic_id="rotation_catchup",
        name="轮动补涨",
        description="轮动环境中，个股中短期刚转强、尚未过度偏离均线，博弈补涨延续。",
        regime_whitelist=["rotation", "weak_rotation"],
        required_datasets=["sector_fund_flow_rank", "stock_hist", "stock_fund_flow", "stock_profile"],
        ranking_rule="prefer mild 5d/10d strength, low extension, and no prior-day acceleration",
        holding_days=3,
        entry_rule={
            "ret_10d_min": 4.0,
            "ret_10d_max": 14.0,
            "ret_5d_min": 0.0,
            "ret_5d_max": 7.0,
            "prev_ret_1d_max": 2.5,
            "ret_1d_min": 0.8,
            "ret_1d_max": 3.5,
            "close_vs_ma10_max_pct": 5.0,
            "pullback_max_from_high_pct": 3.0,
        },
        exit_rule={"take_profit_pct": 7.0, "max_holding_days": 3},
        invalid_rule={"fall_back_into_base": True},
    ),
    LogicSpec(
        logic_id="rotation_base_breakout",
        name="轮动平台突破",
        description="轮动阶段的平台整理个股，在不过热前提下温和突破，博弈短线延续。",
        regime_whitelist=["rotation", "weak_rotation"],
        required_datasets=["stock_hist", "stock_indicators"],
        ranking_rule="prefer moderate 5d/10d trend, low extension, and no prior-day acceleration",
        holding_days=3,
        entry_rule={
            "ret_10d_min": 3.0,
            "ret_10d_max": 13.0,
            "ret_5d_min": 1.0,
            "ret_5d_max": 6.0,
            "prev_ret_1d_max": 2.5,
            "ret_1d_min": 1.0,
            "ret_1d_max": 3.5,
            "close_vs_ma10_max_pct": 4.0,
            "pullback_max_from_high_pct": 2.0,
        },
        exit_rule={"take_profit_pct": 6.0, "max_holding_days": 3},
        invalid_rule={"break_ma10": True, "single_day_drawdown_pct": 4.0},
    ),
    LogicSpec(
        logic_id="ma10_reclaim",
        name="回踩后重回MA10",
        description="短线分歧后重新站回 MA10，适合轮动市场中的修复型低吸。",
        regime_whitelist=["rotation", "weak_rotation"],
        required_datasets=["stock_hist", "stock_indicators"],
        ranking_rule="prefer strong reclaim after prior day shakeout",
        holding_days=2,
        entry_rule={
            "prev_ret_1d_max": -2.5,
            "ret_1d_min": 1.5,
            "ret_1d_max": 5.0,
            "ret_10d_min": -5.0,
            "ret_10d_max": 12.0,
        },
        exit_rule={"take_profit_pct": 5.0, "max_holding_days": 2},
        invalid_rule={"lose_ma10": True, "single_day_drawdown_pct": 4.0},
    ),
    LogicSpec(
        logic_id="weak_rotation_dip_absorb",
        name="弱轮动分歧承接",
        description="弱轮动环境中，前一日分歧回落后次日缩量承接，适合做低吸修复。",
        regime_whitelist=["weak_rotation"],
        required_datasets=["stock_hist", "stock_indicators"],
        ranking_rule="prefer controlled pullback with quick reclaim above ma10",
        holding_days=2,
        entry_rule={
            "prev_ret_1d_min": -5.5,
            "prev_ret_1d_max": -1.5,
            "ret_1d_min": 0.5,
            "ret_1d_max": 3.2,
            "pullback_min_pct": 2.0,
            "pullback_max_pct": 7.0,
        },
        exit_rule={"take_profit_pct": 4.5, "max_holding_days": 2},
        invalid_rule={"lose_recent_low": True, "single_day_drawdown_pct": 4.0},
    ),
    LogicSpec(
        logic_id="weak_rotation_failed_break_reclaim",
        name="弱轮动假跌破回收",
        description="弱轮动中前一日向下假跌破，次日迅速收回关键均线，适合做弱转强低吸。",
        regime_whitelist=["weak_rotation"],
        required_datasets=["stock_hist", "stock_indicators"],
        ranking_rule="prefer false breakdown with reclaim above recent low and ma10",
        holding_days=2,
        entry_rule={
            "prev_ret_1d_min": -6.5,
            "prev_ret_1d_max": -2.0,
            "ret_1d_min": 1.5,
            "ret_1d_max": 4.5,
            "ret_5d_min": -8.0,
            "ret_5d_max": 3.0,
        },
        exit_rule={"take_profit_pct": 5.0, "max_holding_days": 2},
        invalid_rule={"new_low_after_entry": True, "single_day_drawdown_pct": 4.2},
    ),
    LogicSpec(
        logic_id="fund_flow_reversal",
        name="资金反转低吸",
        description="连续弱势后，个股与板块同步出现资金边际修复，博弈短反。",
        regime_whitelist=["weak_rotation", "panic"],
        required_datasets=["stock_fund_flow", "market_fund_flow", "sector_fund_flow_rank", "stock_hist"],
        ranking_rule="prefer improving fund flow with controlled drawdown",
        holding_days=2,
        entry_rule={"need_flow_turn_positive": True, "need_panic_release": True},
        exit_rule={"take_profit_pct": 5.0, "max_holding_days": 2},
        invalid_rule={"new_low_after_entry": True},
    ),
    LogicSpec(
        logic_id="weak_rotation_flat_reclaim",
        name="弱轮动横盘回收",
        description="弱轮动阶段横盘不破位个股，经历一天回踩后重新收回平台上沿，适合先手埋伏。",
        regime_whitelist=["weak_rotation"],
        required_datasets=["stock_hist", "stock_indicators"],
        ranking_rule="prefer flat base with mild 10d strength and fast reclaim",
        holding_days=3,
        entry_rule={
            "ret_10d_min": -2.0,
            "ret_10d_max": 10.0,
            "ret_5d_min": -3.0,
            "ret_5d_max": 4.0,
            "ret_1d_min": 1.0,
            "ret_1d_max": 4.0,
        },
        exit_rule={"take_profit_pct": 5.5, "max_holding_days": 3},
        invalid_rule={"fall_back_into_base": True, "single_day_drawdown_pct": 4.2},
    ),
    LogicSpec(
        logic_id="weak_rotation_tight_range_pop",
        name="弱轮动窄幅转强",
        description="弱轮动阶段经过窄幅整理后向上转强，适合做启动前的先手埋伏。",
        regime_whitelist=["weak_rotation"],
        required_datasets=["stock_hist", "stock_indicators"],
        ranking_rule="prefer tight range base with mild reclaim and low extension",
        holding_days=3,
        entry_rule={
            "ret_10d_min": -1.0,
            "ret_10d_max": 8.0,
            "ret_5d_min": -2.5,
            "ret_5d_max": 3.5,
            "ret_1d_min": 0.8,
            "ret_1d_max": 3.5,
        },
        exit_rule={"take_profit_pct": 5.2, "max_holding_days": 3},
        invalid_rule={"fall_back_into_base": True, "single_day_drawdown_pct": 4.0},
    ),
    LogicSpec(
        logic_id="oversold_rebound",
        name="超跌反抽",
        description="弱轮动阶段的短期超跌股，在急跌后出现日线修复，博弈技术性反抽。",
        regime_whitelist=["weak_rotation", "rotation"],
        required_datasets=["stock_hist", "stock_indicators"],
        ranking_rule="prefer sharp reclaim from recent low without breaking medium-term structure",
        holding_days=2,
        entry_rule={
            "ret_5d_min": -12.0,
            "ret_5d_max": -2.0,
            "prev_ret_1d_max": -3.5,
            "ret_1d_min": 2.0,
            "ret_1d_max": 6.0,
        },
        exit_rule={"take_profit_pct": 5.0, "max_holding_days": 2},
        invalid_rule={"new_low_after_entry": True, "single_day_drawdown_pct": 4.5},
    ),
    LogicSpec(
        logic_id="limit_up_repair",
        name="涨停后修复承接",
        description="前一日强势涨停后，次日不直接A杀，观察缩量回踩后的修复承接。",
        regime_whitelist=["trend", "rotation"],
        required_datasets=["stock_limit_up_pool", "stock_hist", "stock_fund_flow"],
        ranking_rule="prefer shallow retrace and small negative fund flow",
        holding_days=2,
        entry_rule={"must_be_recent_limit_up": True, "retracement_pct_max": 4.0},
        exit_rule={"take_profit_pct": 5.0, "max_holding_days": 2},
        invalid_rule={"retracement_pct_max": 6.0},
    ),
)


def build_default_registry() -> LogicRegistry:
    return LogicRegistry(DEFAULT_LOGICS)
