from __future__ import annotations

from astock.logic_pool.models import LogicSpec
from astock.logic_pool.registry import LogicRegistry


DEFAULT_LOGICS: tuple[LogicSpec, ...] = (
    LogicSpec(
        logic_id="trend_pullback",
        name="主线趋势回踩",
        description="主线方向中，强趋势个股首次回踩短期均线并保持资金承接。",
        regime_whitelist=["trend"],
        required_datasets=["stock_hist", "stock_fund_flow", "stock_indicators", "sector_fund_flow_rank"],
        ranking_rule="prefer positive fund flow and shallow pullback",
        holding_days=3,
        entry_rule={
            "trend_strength_min_5d": 10.0,
            "pullback_max_from_high_pct": 5.5,
            "must_hold_ma5": True,
        },
        exit_rule={"take_profit_pct": 8.0, "max_holding_days": 3},
        invalid_rule={"break_ma10": True, "single_day_drawdown_pct": 5.0},
    ),
    LogicSpec(
        logic_id="leader_first_pullback",
        name="龙头首次分歧回踩",
        description="强势股加速后出现首次温和分歧，观察是否在关键均线上方完成承接。",
        regime_whitelist=["trend", "rotation"],
        required_datasets=["stock_limit_up_pool", "stock_hist", "stock_fund_flow", "stock_spot"],
        ranking_rule="prefer prior-day expansion, mild pullback, and close above ma10",
        holding_days=2,
        entry_rule={
            "prev_ret_1d_min": 5.0,
            "prev_ret_1d_max": 9.9,
            "ret_1d_min": -2.5,
            "ret_1d_max": 2.0,
            "ret_10d_min": 8.0,
            "ret_10d_max": 20.0,
            "pullback_min_from_high_pct": 1.0,
            "pullback_max_from_high_pct": 6.0,
        },
        exit_rule={"take_profit_pct": 6.0, "max_holding_days": 2},
        invalid_rule={"lose_previous_day_low": True},
    ),
    LogicSpec(
        logic_id="rotation_catchup",
        name="轮动补涨",
        description="轮动环境中，个股中短期刚转强、尚未过度偏离均线，博弈补涨延续。",
        regime_whitelist=["rotation", "weak_rotation"],
        required_datasets=["sector_fund_flow_rank", "stock_hist", "stock_fund_flow", "stock_profile"],
        ranking_rule="prefer mild 5d/10d strength, low extension, and no prior-day acceleration",
        holding_days=3,
        entry_rule={
            "ret_10d_min": 4.0,
            "ret_10d_max": 14.0,
            "ret_5d_min": 0.0,
            "ret_5d_max": 7.0,
            "prev_ret_1d_max": 2.5,
            "ret_1d_min": 0.8,
            "ret_1d_max": 3.5,
            "close_vs_ma10_max_pct": 5.0,
            "pullback_max_from_high_pct": 3.0,
        },
        exit_rule={"take_profit_pct": 7.0, "max_holding_days": 3},
        invalid_rule={"fall_back_into_base": True},
    ),
    LogicSpec(
        logic_id="rotation_base_breakout",
        name="轮动平台突破",
        description="轮动阶段的平台整理个股，在不过热前提下温和突破，博弈短线延续。",
        regime_whitelist=["rotation", "weak_rotation"],
        required_datasets=["stock_hist", "stock_indicators"],
        ranking_rule="prefer moderate 5d/10d trend, low extension, and no prior-day acceleration",
        holding_days=3,
        entry_rule={
            "ret_10d_min": 3.0,
            "ret_10d_max": 13.0,
            "ret_5d_min": 1.0,
            "ret_5d_max": 6.0,
            "prev_ret_1d_max": 2.5,
            "ret_1d_min": 1.0,
            "ret_1d_max": 3.5,
            "close_vs_ma10_max_pct": 4.0,
            "pullback_max_from_high_pct": 2.0,
        },
        exit_rule={"take_profit_pct": 6.0, "max_holding_days": 3},
        invalid_rule={"break_ma10": True, "single_day_drawdown_pct": 4.0},
    ),
    LogicSpec(
        logic_id="ma10_reclaim",
        name="回踩后重回MA10",
        description="短线分歧后温和收复 MA10，要求位置不高、前一日有洗盘痕迹。",
        regime_whitelist=["rotation", "weak_rotation"],
        required_datasets=["stock_hist", "stock_indicators"],
        ranking_rule="prefer moderate reclaim from shallow drawdown close to ma10",
        holding_days=2,
        entry_rule={
            "prev_ret_1d_min": -4.5,
            "prev_ret_1d_max": -1.5,
            "ret_1d_min": 1.2,
            "ret_1d_max": 3.8,
            "ret_5d_min": -3.0,
            "ret_5d_max": 5.0,
            "ret_10d_min": -2.0,
            "ret_10d_max": 8.0,
            "close_vs_ma10_max_pct": 3.5,
            "pullback_min_from_high_pct": 0.5,
            "pullback_max_from_high_pct": 4.0,
        },
        exit_rule={"take_profit_pct": 5.0, "max_holding_days": 2},
        invalid_rule={"lose_ma10": True, "single_day_drawdown_pct": 4.0},
    ),
    LogicSpec(
        logic_id="weak_rotation_dip_absorb",
        name="弱轮动分歧承接",
        description="弱轮动环境中，前一日分歧回落后次日缩量承接，适合做低吸修复。",
        regime_whitelist=["weak_rotation"],
        required_datasets=["stock_hist", "stock_indicators"],
        ranking_rule="prefer controlled pullback with quick reclaim above ma10",
        holding_days=2,
        entry_rule={
            "prev_ret_1d_min": -5.5,
            "prev_ret_1d_max": -1.5,
            "ret_1d_min": 0.5,
            "ret_1d_max": 3.5,
            "pullback_min_pct": 1.5,
            "pullback_max_pct": 7.0,
        },
        exit_rule={"take_profit_pct": 4.5, "max_holding_days": 2},
        invalid_rule={"lose_recent_low": True, "single_day_drawdown_pct": 4.0},
    ),
    LogicSpec(
        logic_id="weak_rotation_failed_break_reclaim",
        name="弱轮动假跌破回收",
        description="弱轮动中出现向下假跌破，随后快速收回近期低点与 MA10，博弈修复。",
        regime_whitelist=["weak_rotation"],
        required_datasets=["stock_hist", "stock_indicators"],
        ranking_rule="prefer shallow false breakdown and reclaim above recent low / ma10",
        holding_days=2,
        entry_rule={
            "prev_ret_1d_min": -6.0,
            "prev_ret_1d_max": -2.0,
            "ret_1d_min": 1.0,
            "ret_1d_max": 4.0,
            "ret_5d_min": -6.0,
            "ret_5d_max": 2.0,
            "pullback_min_from_high_pct": 1.5,
            "pullback_max_from_high_pct": 7.0,
        },
        exit_rule={"take_profit_pct": 5.0, "max_holding_days": 2},
        invalid_rule={"new_low_after_entry": True, "single_day_drawdown_pct": 4.2},
    ),
    LogicSpec(
        logic_id="fund_flow_reversal",
        name="资金反转低吸",
        description="连续弱势后，个股与板块同步出现资金边际修复，博弈短反。",
        regime_whitelist=["weak_rotation", "panic"],
        required_datasets=["stock_fund_flow", "market_fund_flow", "sector_fund_flow_rank", "stock_hist"],
        ranking_rule="prefer improving fund flow with controlled drawdown",
        holding_days=2,
        entry_rule={"need_flow_turn_positive": True, "need_panic_release": True},
        exit_rule={"take_profit_pct": 5.0, "max_holding_days": 2},
        invalid_rule={"new_low_after_entry": True},
    ),
    LogicSpec(
        logic_id="weak_rotation_flat_reclaim",
        name="弱轮动横盘回收",
        description="弱轮动阶段横盘不破位个股，经历一天回踩后重新收回平台上沿，适合先手埋伏。",
        regime_whitelist=["weak_rotation"],
        required_datasets=["stock_hist", "stock_indicators"],
        ranking_rule="prefer flat base with mild 10d strength and fast reclaim",
        holding_days=3,
        entry_rule={
            "ret_10d_min": -2.0,
            "ret_10d_max": 10.0,
            "ret_5d_min": -3.0,
            "ret_5d_max": 4.0,
            "ret_1d_min": 1.0,
            "ret_1d_max": 4.0,
        },
        exit_rule={"take_profit_pct": 5.5, "max_holding_days": 3},
        invalid_rule={"fall_back_into_base": True, "single_day_drawdown_pct": 4.2},
    ),
    LogicSpec(
        logic_id="oversold_rebound",
        name="超跌反抽",
        description="短期急跌后出现温和修复，博弈弱轮动中的技术性反抽。",
        regime_whitelist=["weak_rotation", "rotation"],
        required_datasets=["stock_hist", "stock_indicators"],
        ranking_rule="prefer oversold repair close to recent low without overextension",
        holding_days=2,
        entry_rule={
            "ret_5d_min": -10.0,
            "ret_5d_max": -3.0,
            "ret_10d_min": -18.0,
            "ret_10d_max": 2.0,
            "prev_ret_1d_max": -2.5,
            "ret_1d_min": 1.5,
            "ret_1d_max": 5.0,
        },
        exit_rule={"take_profit_pct": 5.0, "max_holding_days": 2},
        invalid_rule={"new_low_after_entry": True, "single_day_drawdown_pct": 4.5},
    ),
    LogicSpec(
        logic_id="limit_up_repair",
        name="涨停后修复承接",
        description="前一日强势涨停后，次日出现温和分歧但不破位，博弈修复承接。",
        regime_whitelist=["trend", "rotation"],
        required_datasets=["stock_limit_up_pool", "stock_hist", "stock_fund_flow"],
        ranking_rule="prefer prior-day expansion and shallow second-day retrace above ma10",
        holding_days=2,
        entry_rule={
            "prev_ret_1d_min": 7.5,
            "prev_ret_1d_max": 11.0,
            "ret_1d_min": -3.5,
            "ret_1d_max": 1.5,
            "close_vs_prev_close_min_pct": -4.0,
        },
        exit_rule={"take_profit_pct": 5.0, "max_holding_days": 2},
        invalid_rule={"retracement_pct_max": 6.0},
    ),
)


def build_default_registry() -> LogicRegistry:
    registry = LogicRegistry(DEFAULT_LOGICS)
    try:
        from astock.storage.duckdb import DuckDbStorage

        for spec in DuckDbStorage().load_promoted_logic_specs():
            registry.register(spec)
    except Exception:
        pass
    return registry
